# Generated by Django 5.2.7 on 2025-11-04 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('official_communication', models.CharField(max_length=255)),
                ('email_domain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_type', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('elective', 'Elective')], max_length=50)),
                ('enrolled_students', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.institute'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=100, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.department')),
                ('electives', models.ManyToManyField(blank=True, related_name='elective_students', to='institutes.course')),
                ('majors', models.ManyToManyField(blank=True, related_name='major_students', to='institutes.course')),
                ('minors', models.ManyToManyField(blank=True, related_name='minor_students', to='institutes.course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('total_theory_hours', models.IntegerField()),
                ('total_practical_hour', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.course')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.department')),
                ('primary_subjects', models.ManyToManyField(related_name='primary_faculties', to='institutes.subject')),
                ('secondary_subjects', models.ManyToManyField(blank=True, related_name='secondary_faculties', to='institutes.subject')),
            ],
        ),
    ]
